[tool.yapf]
based_on_style = 'google'

[tool.yapfignore]
ignore_patterns = ['build/']

[tool.isort]
profile = 'google'

[tool.pylint.MASTER]
load-plugins = ['pylint.extensions.mccabe', 'pylint.extensions.docparams']

[tool.pylint.messages_control]
enable = [
    'F',
    'E',
    'anomalous-backslash-in-string',
    'bad-format-string',
    'bad-open-mode',
    'binary-op-exception',
    'duplicate-key',
    'global-variable-not-assigned',
    'unnecessary-semicolon',
    'unreachable',
]
disable = [
    'bad-indentation',
    'c-extension-no-member',
    'fixme',
    'import-error',
    'invalid-name',
    'missing-class-docstring',
    'missing-function-docstring',
    'missing-module-docstring',
    'missing-raises-doc',
    'missing-return-doc',
    'protected-access',
    'redefined-outer-name',
    'superfluous-parens',
    'too-few-public-methods',
    'too-many-arguments',
    'trailing-whitespace',
    'unused-argument',
    'unused-import',
    'unused-variable',
    'wrong-import-order',
]

[tool.mypy]
disable_error_code = ['var-annotated', 'import']

[tool.pytest.ini_options]
addopts = '-v'
